from app.downloader.aria2c.torrent import (
    SITES,
    DownloadResult,
    MagnetioRPCError,
    add_trackers_to_magnet,
    download_torrent_async,
    download_via_aria2_async,
    fetch_latest_trackers,
    format_search_results_html,
    get_tracker_string,
    get_trackers,
    initiate_search_tools,
    search_torrents,
    search_torrents_rpc,
    start_aria2_daemon,
    stop_aria2_daemon,
    telegraph_helper,
)

__all__ = [
    "SITES",
    "DownloadResult",
    "MagnetioRPCError",
    "add_trackers_to_magnet",
    "download_torrent_async",
    "download_via_aria2_async",
    "fetch_latest_trackers",
    "format_search_results_html",
    "get_tracker_string",
    "get_trackers",
    "initiate_search_tools",
    "search_torrents",
    "search_torrents_rpc",
    "start_aria2_daemon",
    "stop_aria2_daemon",
    "telegraph_helper",
]
